### ISSUE TITLE
Test "first run" funtionality

### ISSUE THREAD

**Issue by mass** [mass/twinrinks-mobile#10]
Sometimes when starting the app for the first time, it is buggy due to the files not existing and no teams being selected and such. I want to test this more and ensure the app works flawlessly.

**Comment by mass** [comment]
I don't see anything wrong with the first-run, post an issue if something is found.

**Comment by avp** [comment]
Why on earth did you make this an issue and leave it open for days if there was no bug? I'm confused.

**Comment by mass** [comment]
I thought there was a bug. As I did more testing, I realized there wasn't. Lol.
